version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run:
          name: "Retrieve dependencies"
          command: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run:
          name: "Pull Submodules"
          command: git submodule update --init --recursive --remote

      - run:
          name: "Build project"
          command: mvn clean install
